13681/framework/evgeniy
cactuscake/sw-academy pull request #3
Opened 2024-08-02 10:08 UTC by cactuscake

реализована логика страницы и взаимодействие с БД
задача:[13681]()

2024-08-02 12:39 UTC, nacretion requested changes

2024-08-02 12:39 UTC, nacretion commented on src/index.php
> +    <?php $APPLICATION->includeComponent("header", ".default", [ "logo" => "МЕБЕЛЬ",
Отступы некорректные, но в includeComponent можно. Смотри чтобы в других местах такого не было

2024-08-02 12:39 UTC, nacretion commented on src/index.php
> +$descriptionItems = ["Наша компания изготавливает кухни по индивидуальному проекту, что позволит самостоятельно выбрать стиль и цвет каждого изделия.",
Исправить отступы
1. отступы от левого края
2. либо все элементы массива с новой строки, либо все в одну

2024-08-02 12:39 UTC, nacretion commented on src/framework/framework.php
> +$DB = new CDatabase();
Зачем получать экземпляр одиночки?

2024-08-02 12:39 UTC, nacretion commented on src/framework/framework.php
> +$CONFIG = Config::getInstanse();
Раз одиночка, то незачем глобальную переменную делать

2024-08-02 12:39 UTC, nacretion commented on src/framework/Base/CMain.php
> +        // $arParams = array_merge($arParams, $params);
Комментарий лишний

2024-08-02 12:39 UTC, nacretion commented on src/framework/Base/CDatabase.php
> +    public \PDO $connection;
Публичное поле, которое легко подменить извне - плохо

2024-08-02 12:39 UTC, nacretion commented on src/framework/Base/Models/Model.php
> +        $data['id'] = $id;
бесполезная строка. id нам незачем менять, да и это невозможно

2024-08-02 12:39 UTC, nacretion commented on src/framework/Base/Models/Model.php
> +        $fieldName = strtolower(substr($name, 3));
Если пытаюсь изменить свойство, которого нет в fillable - он даст это сделать
А не должен

2024-08-02 12:39 UTC, nacretion commented on src/framework/Base/Validators/UserValidator.php
> +        UserValidator::clearErrors();
Связность слишком большая, нужно использовать static

2024-08-02 12:39 UTC, nacretion commented on src/framework/Base/Validators/UserValidator.php
> +class UserValidator
Нужно описать базовый валидатор. А в этом оставить лишь набор правил и сообщений об ошибке

2024-08-05 10:28 UTC, evgeny89 commented on src/framework/Base/Validators/Validator.php
> +        if ($data["name"] !== null) {
лучше match использовать

2024-08-05 10:53 UTC, merged